In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import os
import re
from pathlib import Path
from glob import glob
from loguru import logger
import cdblib
import numpy as np

In [3]:
# !pip install pure-cdb

In [4]:
#.gitignore
#*.ipynb*
# os.path.isdir(folders[5])
dir_path = os.getcwd()
if not os.path.exists(f'{dir_path}/output'):
    result_path = os.makedirs(f'{dir_path}/output')
# result_path

In [5]:
dir_path = os.getcwd()
folders = sorted(Path(dir_path).glob('D/AB029/'))
# folders = folders[1:3]
folders

[PosixPath('/home/pinky/Documents/p_projects/rabina_file/D/AB029')]

In [6]:
for i in folders:
    files = sorted(Path(i).glob('*.TXT'))
    folder_name = str(i).split('/')[-1]
    logger.info(f"Calculating values for folder: {folder_name} ...")
    results = []
    for file in files:
        file_name = os.path.splitext(file.name)[0]
        angle = file_name.split('_')[-1]
        logger.info(f"Reading for file: {file_name} and angle: {angle}")
        with open(file, 'r') as f:
            lines = f.readlines()
            del lines[:2]
            final_lines = [re.split('\s+', l.strip()) for l in lines]
            df = pd.DataFrame(final_lines[1:], columns=final_lines[0])
#             df = df.drop(columns=['NODE'])
            values = [angle, 
                      int(float(df[df['EQUIVALENTSTRESS']==df['EQUIVALENTSTRESS'].max()]['NODE'].iloc[0])), df['EQUIVALENTSTRESS'].max(), 
                      int(float(df[df['EQUIVALENTSTRESS']==df['EQUIVALENTSTRESS'].min()]['NODE'].iloc[0])), df['EQUIVALENTSTRESS'].min(), 
                      int(float(df[df['PRINCIPALSTRESS']==df['PRINCIPALSTRESS'].max()]['NODE'].iloc[0])), df['PRINCIPALSTRESS'].max(), 
                      int(float(df[df['PRINCIPALSTRESS']==df['PRINCIPALSTRESS'].min()]['NODE'].iloc[0])), df['PRINCIPALSTRESS'].min(), 
                      int(float(df[df['EQVSTRAIN']==df['EQVSTRAIN'].max()]['NODE'].iloc[0])), df['EQVSTRAIN'].max(), 
                      int(float(df[df['EQVSTRAIN']==df['EQVSTRAIN'].min()]['NODE'].iloc[0])), df['EQVSTRAIN'].min(), 
                      int(float(df[df['PRINCIPALSTRAIN']==df['PRINCIPALSTRAIN'].max()]['NODE'].iloc[0])), df['PRINCIPALSTRAIN'].max(), 
                      int(float(df[df['PRINCIPALSTRAIN']==df['PRINCIPALSTRAIN'].min()]['NODE'].iloc[0])), df['PRINCIPALSTRAIN'].min()]
            logger.info(f"Values for angle: {angle} calculated!")
            results.append(values)
    #         sorting results on the basis of angle
            sorted_result = sorted(results, key=lambda x: int(x[0]))
    results_df = pd.DataFrame(sorted_result, columns=['Angle', 
                                                      "NODE_EQUIVALENTSTRESS_max", "EQUIVALENTSTRESS_max", 
                                                      "NODE_EQUIVALENTSTRESS_min", "EQUIVALENTSTRESS_min", 
                                                      "NODE_PRINCIPALSTRESS_max", "PRINCIPALSTRESS_max", 
                                                      "NODE_PRINCIPALSTRESS_min", "PRINCIPALSTRESS_min", 
                                                      "NODE_EQVSTRAIN_max", "EQVSTRAIN_max", 
                                                      "NODE_EQVSTRAIN_min", "EQVSTRAIN_min", 
                                                      "NODE_PRINCIPALSTRAIN_max", "PRINCIPALSTRAIN_max", 
                                                      "NODE_PRINCIPALSTRAIN_min", "PRINCIPALSTRAIN_min",])
    if not os.path.exists(f'{dir_path}/output'):
        os.makedirs(f'{dir_path}/output')
    results_df.to_csv(f"{dir_path}/output/{folder_name}.csv")

2020-06-16 18:56:21.623 | INFO     | __main__:<module>:4 - Calculating values for folder: AB029 ...
2020-06-16 18:56:21.625 | INFO     | __main__:<module>:9 - Reading for file: TRY_0 and angle: 0
2020-06-16 18:56:23.670 | INFO     | __main__:<module>:25 - Values for angle: 0 calculated!
2020-06-16 18:56:23.671 | INFO     | __main__:<module>:9 - Reading for file: TRY_10 and angle: 10
2020-06-16 18:56:23.808 | INFO     | __main__:<module>:25 - Values for angle: 10 calculated!
2020-06-16 18:56:23.808 | INFO     | __main__:<module>:9 - Reading for file: TRY_120 and angle: 120
2020-06-16 18:56:23.965 | INFO     | __main__:<module>:25 - Values for angle: 120 calculated!
2020-06-16 18:56:23.966 | INFO     | __main__:<module>:9 - Reading for file: TRY_15 and angle: 15
2020-06-16 18:56:25.588 | INFO     | __main__:<module>:25 - Values for angle: 15 calculated!
2020-06-16 18:56:25.589 | INFO     | __main__:<module>:9 - Reading for file: TRY_20 and angle: 20
2020-06-16 18:56:26.782 | INFO     | _

In [7]:
results_df.head()

Angle  NODE_EQUIVALENTSTRESS_max EQUIVALENTSTRESS_max  \
0     0                      12674          0.99988E+01   
1    10                       1092          0.99995E+01   
2    15                       4411          0.99944E+01   
3    20                       6845          0.99996E-01   
4    30                       8070          0.99997E+01   

   NODE_EQUIVALENTSTRESS_min EQUIVALENTSTRESS_min  NODE_PRINCIPALSTRESS_max  \
0                         29          0.00000E+00                      9750   
1                         29          0.00000E+00                      9378   
2                         29          0.00000E+00                     11104   
3                         29          0.00000E+00                      4457   
4                         29          0.00000E+00                      7222   

  PRINCIPALSTRESS_max  NODE_PRINCIPALSTRESS_min PRINCIPALSTRESS_min  \
0         0.99971E+00                       321        -0.10003E+00   
1         0.99993E+00                     10124        -0.10003E+00   
2         0.99993E+01                     11066        -0.10010E+01   
3         0.99995E+00                      2965        -0.10010E-01   
4         0.99994E-01                     13236        -0.10002E+02   

   NODE_EQVSTRAIN_max EQVSTRAIN_max  NODE_EQVSTRAIN_min EQVSTRAIN_min  \
0               12159   0.99988E-03                  29   0.00000E+00   
1                9288   0.99999E-03                  29   0.00000E+00   
2                5650   0.99954E-03                  29   0.00000E+00   
3                4866   0.99975E-02                  29   0.00000E+00   
4                6662   0.99955E-03                  29   0.00000E+00   

   NODE_PRINCIPALSTRAIN_max PRINCIPALSTRAIN_max  NODE_PRINCIPALSTRAIN_min  \
0                      2027         0.99996E-03                      1231   
1                      6960         0.99998E-03                      8916   
2                      7080         0.99979E-02                      3496   
3                     11063         0.99986E-03                      6608   
4                      1072         0.99913E-03                      8601   

  PRINCIPALSTRAIN_min  
0        -0.30686E-05  
1        -0.16048E-04  
2        -0.11617E-04  
3        -0.14572E-04  
4        -0.23716E-03

# find materials and elements data from cdb file

In [8]:
for i in folders:
    cdb_file = sorted(Path(i).glob('*.cdb'))
    with open(cdb_file[0], 'r') as f:
        data = f.readlines()


In [9]:
# order of cdb file: node -> element -> component -> material

In [9]:
for i, text in enumerate(data):
    if "Elements" in text:
        start_element = i
    if "Component" in text:
        start_component = i
    if "MATERIALS" in text:
        start_material = i
    if "Nodes for the whole assembly" in text:
        start_nodes_xyz = i
nodes_xyz_data = [text.strip() for i, text in enumerate(data) if (i >= start_nodes_xyz and i < start_element)]
element_data = [text.strip() for i, text in enumerate(data) if (i >= start_element and i < start_component)]
material_data = [text.strip() for i, text in enumerate(data) if (i >= start_material)]

# processing nodes_xyz data and create df and setting the datatype of node as int (to make same as results_df)

In [10]:
nodes_xyz_data = [re.split('\s+', l.strip()) for l in nodes_xyz_data[3:-2]]
nodes_xyz_df = pd.DataFrame(nodes_xyz_data, columns=['NODE_PRINCIPALSTRAIN_max', 'A', 'B', 'x', 'y', 'z'])
nodes_xyz_df['NODE_PRINCIPALSTRAIN_max']=nodes_xyz_df['NODE_PRINCIPALSTRAIN_max'].astype(int)

# taking subset with principal strain max data only

In [11]:
principal_strain_df = results_df[["NODE_PRINCIPALSTRAIN_max", "PRINCIPALSTRAIN_max"]]

# merge two df and extracting x,y,z value respective to principal strain node

In [12]:
p_strain_xyz = pd.merge(principal_strain_df, nodes_xyz_df, on='NODE_PRINCIPALSTRAIN_max')

In [13]:
p_strain_xyz

NODE_PRINCIPALSTRAIN_max PRINCIPALSTRAIN_max  A  B                  x  \
0                      2027         0.99996E-03  0  0  -9.324880000e+001   
1                      6960         0.99998E-03  0  0  -1.444001000e+002   
2                      7080         0.99979E-02  0  0  -1.453011000e+002   
3                     11063         0.99986E-03  0  0  -1.214818000e+002   
4                      1072         0.99913E-03  0  0  -1.160732000e+002   
5                     13483         0.99985E-02  0  0  -8.603440000e+001   
6                     11026         0.99987E-03  0  0  -1.204789000e+002   
7                     11557         0.99990E-04  0  0  -1.459944000e+002   
8                     13142         0.99959E-02  0  0  -1.038145000e+002   

                   y                 z  
0  -1.831304000e+002  1.025114400e+003  
1  -1.741127000e+002  1.430553500e+003  
2  -1.848318000e+002  1.377479200e+003  
3  -1.756688000e+002  1.436469400e+003  
4  -1.898914000e+002  1.399942500e+003  
5  -1.735906000e+002  1.032548300e+003  
6  -1.775304000e+002  1.001962400e+003  
7  -2.042148000e+002  1.206432700e+003  
8  -1.843488000e+002  1.446852300e+003

# extending limits of x,y,z: add range of +/-2mm = 0.002

In [14]:
nodes_xyz_df.head()

NODE_PRINCIPALSTRAIN_max  A  B                  x                  y  \
0                         1  0  0  -1.450981000e+002  -1.775839000e+002   
1                         2  0  0  -1.481123000e+002  -1.788328000e+002   
2                         3  0  0  -1.461585000e+002  -1.787129000e+002   
3                         4  0  0  -1.460607000e+002  -1.834105000e+002   
4                         5  0  0  -1.045351000e+002  -1.893952000e+002   

                  z  
0  1.352043400e+003  
1  1.347468800e+003  
2  1.346927900e+003  
3  1.350052300e+003  
4  1.453299500e+003

In [15]:
nodes_xyz_df['x'] = nodes_xyz_df['x'].astype(float)
nodes_xyz_df['y'] = nodes_xyz_df['y'].astype(float)
nodes_xyz_df['z'] = nodes_xyz_df['z'].astype(float)

In [16]:
p_strain_xyz['x_max'] = p_strain_xyz['x'].astype(float) + 2
p_strain_xyz['x_min'] = p_strain_xyz['x'].astype(float) - 2
p_strain_xyz['y_max'] = p_strain_xyz['y'].astype(float) + 4
p_strain_xyz['y_min'] = p_strain_xyz['y'].astype(float) - 4
p_strain_xyz['z_max'] = p_strain_xyz['z'].astype(float) + 2
p_strain_xyz['z_min'] = p_strain_xyz['z'].astype(float) - 2

In [17]:
p_strain_xyz

NODE_PRINCIPALSTRAIN_max PRINCIPALSTRAIN_max  A  B                  x  \
0                      2027         0.99996E-03  0  0  -9.324880000e+001   
1                      6960         0.99998E-03  0  0  -1.444001000e+002   
2                      7080         0.99979E-02  0  0  -1.453011000e+002   
3                     11063         0.99986E-03  0  0  -1.214818000e+002   
4                      1072         0.99913E-03  0  0  -1.160732000e+002   
5                     13483         0.99985E-02  0  0  -8.603440000e+001   
6                     11026         0.99987E-03  0  0  -1.204789000e+002   
7                     11557         0.99990E-04  0  0  -1.459944000e+002   
8                     13142         0.99959E-02  0  0  -1.038145000e+002   

                   y                 z     x_max     x_min     y_max  \
0  -1.831304000e+002  1.025114400e+003  -91.2488  -95.2488 -179.1304   
1  -1.741127000e+002  1.430553500e+003 -142.4001 -146.4001 -170.1127   
2  -1.848318000e+002  1.377479200e+003 -143.3011 -147.3011 -180.8318   
3  -1.756688000e+002  1.436469400e+003 -119.4818 -123.4818 -171.6688   
4  -1.898914000e+002  1.399942500e+003 -114.0732 -118.0732 -185.8914   
5  -1.735906000e+002  1.032548300e+003  -84.0344  -88.0344 -169.5906   
6  -1.775304000e+002  1.001962400e+003 -118.4789 -122.4789 -173.5304   
7  -2.042148000e+002  1.206432700e+003 -143.9944 -147.9944 -200.2148   
8  -1.843488000e+002  1.446852300e+003 -101.8145 -105.8145 -180.3488   

      y_min      z_max      z_min  
0 -187.1304  1027.1144  1023.1144  
1 -178.1127  1432.5535  1428.5535  
2 -188.8318  1379.4792  1375.4792  
3 -179.6688  1438.4694  1434.4694  
4 -193.8914  1401.9425  1397.9425  
5 -177.5906  1034.5483  1030.5483  
6 -181.5304  1003.9624   999.9624  
7 -208.2148  1208.4327  1204.4327  
8 -188.3488  1448.8523  1444.8523

# calculating extra nodes 

In [18]:
extra_principal_strain_node = [[]]*len(results_df)
node_df_node = nodes_xyz_df['NODE_PRINCIPALSTRAIN_max'].values # all nodes values
node_df_x = nodes_xyz_df['x'].values
node_df_y = nodes_xyz_df['y'].values
node_df_z = nodes_xyz_df['z'].values
x_max = p_strain_xyz['x_max'].values
x_min = p_strain_xyz['x_min'].values
y_max = p_strain_xyz['y_max'].values
y_min = p_strain_xyz['y_min'].values
z_max = p_strain_xyz['z_max'].values
z_min = p_strain_xyz['z_min'].values

for i in range(len(x_max)):
    for j in np.where(((x_min[i] <= node_df_x) & (node_df_x <= x_max[i])) & 
                      ((y_min[i] <= node_df_y) & (node_df_y <= y_max[i])) & 
                      ((z_min[i] <= node_df_z) & (node_df_z <= z_max[i]))): 
        extra_principal_strain_node[i] = node_df_node[j]
results_df['EXTRA_NODE_PRINCIPALSTRAIN'] = extra_principal_strain_node

In [19]:
results_df['EXTRA_NODE_PRINCIPALSTRAIN']

0                                               [2027]
1    [892, 4524, 6958, 6960, 7294, 7295, 12609, 12700]
2                                         [7080, 7081]
3                                              [11063]
4                                               [1072]
5                                        [4793, 13483]
6                                  [4827, 9620, 11026]
7                                       [11557, 12581]
8                                              [13142]
Name: EXTRA_NODE_PRINCIPALSTRAIN, dtype: object

# processing element_data

In [56]:
element_data = [re.split('\s+', l.strip()) for l in element_data[4:-1]]

AttributeError: 'list' object has no attribute 'strip'

In [21]:
# results_df

In [22]:
element_df = pd.DataFrame(element_data, columns=['Element', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'Node4', 'Node3', 'Node2', 'Node1'])

In [23]:
element_df.head()

Element  B  C  D  E  F  G  H  I  J  K Node4 Node3 Node2 Node1
0      25  1  1  0  0  0  0  0  4  0  1     1     2     3     4
1      12  1  1  0  0  0  0  0  4  0  2     5     6     7     8
2      19  1  1  0  0  0  0  0  4  0  3     9    10    11    12
3      43  1  1  0  0  0  0  0  4  0  4    13    14    15    16
4      17  1  1  0  0  0  0  0  4  0  5    17    18    19    20

In [24]:
elements = (element_df['Element'].astype(float).astype(int)).values
nodes1 = (element_df['Node1'].astype(int)).values
nodes2 = (element_df['Node2'].astype(int)).values
nodes3 = (element_df['Node3'].astype(int)).values
nodes4 = (element_df['Node4'].astype(int)).values
node_e_stress_max = results_df['NODE_EQUIVALENTSTRESS_max'].values
# node_e_stress_min = results_df['NODE_EQUIVALENTSTRESS_min'].values
# node_p_stress_max = results_df['NODE_PRINCIPALSTRESS_max'].values
# node_p_stress_min = results_df['NODE_PRINCIPALSTRESS_min'].values
# node_e_strain_max = results_df['NODE_EQVSTRAIN_max'].values
# node_e_strain_min = results_df['NODE_EQVSTRAIN_min'].values
node_p_strain_max = results_df['NODE_PRINCIPALSTRAIN_max'].values
node_p_strain_min = results_df['NODE_PRINCIPALSTRAIN_min'].values

In [25]:
# element_e_stress_max = [[]]*len(node_e_stress_max)
# element_e_stress_min = [[]]*len(node_e_stress_min)
# element_p_stress_max = [[]]*len(node_p_stress_max)
# element_p_stress_min = [[]]*len(node_p_stress_min)
# element_e_strain_max = [[]]*len(node_e_strain_max)
# element_e_strain_min = [[]]*len(node_e_strain_min)
element_p_strain_max = [[]]*len(node_p_strain_max)
element_p_strain_min = [[]]*len(node_p_strain_min)

for i in range(len(node_e_stress_max)):
#     for i1 in np.where(node_e_stress_max[i] == nodes):
#         element_e_stress_max[i] = elements[i1]
#     for i2 in np.where(node_e_stress_min[i] == nodes):
#         element_e_stress_min[i] = elements[i2]
#     for i3 in np.where(node_p_stress_max[i] == nodes):
#         element_p_stress_max[i] = elements[i3]
#     for i4 in np.where(node_p_stress_min[i] == nodes):
#         element_p_stress_min[i] = elements[i4]
#     for i5 in np.where(node_e_strain_max[i] == nodes):
#         element_e_strain_max[i] = elements[i5]
#     for i6 in np.where(node_e_strain_min[i] == nodes):
#         element_e_strain_min[i] = elements[i6]
    for i7 in np.where((node_p_strain_max[i] == nodes1) | 
                       (node_p_strain_max[i] == nodes2)):
        element_p_strain_max[i] = set(elements[i7])            
    for i8 in np.where((node_p_strain_min[i] == nodes1) | 
                       (node_p_strain_max[i] == nodes2)):
        element_p_strain_min[i] = set(elements[i8])
    

In [26]:
# results_df['ELEMENT_EQUIVALENTSTRESS_max'] = element_e_stress_max
# results_df['ELEMENT_EQUIVALENTSTRESS_min'] = element_e_stress_min
# results_df['ELEMENT_PRINCIPALSTRESS_max'] = element_p_stress_max
# results_df['ELEMENT_PRINCIPALSTRESS_min'] = element_p_stress_min
# results_df['ELEMENT_EQVSTRAIN_max'] = element_e_strain_max
# results_df['ELEMENT_EQVSTRAIN_min'] = element_e_strain_min
results_df['ELEMENT_PRINCIPALSTRAIN_max'] = element_p_strain_max
results_df['ELEMENT_PRINCIPALSTRAIN_min'] = element_p_strain_min


In [27]:
results_df

Angle  NODE_EQUIVALENTSTRESS_max EQUIVALENTSTRESS_max  \
0     0                      12674          0.99988E+01   
1    10                       1092          0.99995E+01   
2    15                       4411          0.99944E+01   
3    20                       6845          0.99996E-01   
4    30                       8070          0.99997E+01   
5    45                       5129          0.99969E-02   
6    60                       4600          0.99972E+00   
7    90                       8345          0.99969E+00   
8   120                       2877          0.99993E+00   

   NODE_EQUIVALENTSTRESS_min EQUIVALENTSTRESS_min  NODE_PRINCIPALSTRESS_max  \
0                         29          0.00000E+00                      9750   
1                         29          0.00000E+00                      9378   
2                         29          0.00000E+00                     11104   
3                         29          0.00000E+00                      4457   
4                         29          0.00000E+00                      7222   
5                         29          0.00000E+00                     10444   
6                         29          0.00000E+00                      4517   
7                         29          0.00000E+00                      7944   
8                         29          0.00000E+00                      5039   

  PRINCIPALSTRESS_max  NODE_PRINCIPALSTRESS_min PRINCIPALSTRESS_min  \
0         0.99971E+00                       321        -0.10003E+00   
1         0.99993E+00                     10124        -0.10003E+00   
2         0.99993E+01                     11066        -0.10010E+01   
3         0.99995E+00                      2965        -0.10010E-01   
4         0.99994E-01                     13236        -0.10002E+02   
5         0.99991E+00                      7152        -0.10001E+00   
6         0.99959E+00                      4117        -0.10007E+01   
7         0.99981E-01                     12398        -0.10005E+01   
8         0.99964E+00                      1253        -0.10028E+01   

   NODE_EQVSTRAIN_max EQVSTRAIN_max  NODE_EQVSTRAIN_min EQVSTRAIN_min  \
0               12159   0.99988E-03                  29   0.00000E+00   
1                9288   0.99999E-03                  29   0.00000E+00   
2                5650   0.99954E-03                  29   0.00000E+00   
3                4866   0.99975E-02                  29   0.00000E+00   
4                6662   0.99955E-03                  29   0.00000E+00   
5                6274   0.99992E-03                  29   0.00000E+00   
6                7678   0.99960E-03                  29   0.00000E+00   
7                 614   0.99961E-03                  29   0.00000E+00   
8               13775   0.99977E-02                  29   0.00000E+00   

   NODE_PRINCIPALSTRAIN_max PRINCIPALSTRAIN_max  NODE_PRINCIPALSTRAIN_min  \
0                      2027         0.99996E-03                      1231   
1                      6960         0.99998E-03                      8916   
2                      7080         0.99979E-02                      3496   
3                     11063         0.99986E-03                      6608   
4                      1072         0.99913E-03                      8601   
5                     13483         0.99985E-02                      1231   
6                     11026         0.99987E-03                      6972   
7                     11557         0.99990E-04                       764   
8                     13142         0.99959E-02                      3994   

  PRINCIPALSTRAIN_min                         EXTRA_NODE_PRINCIPALSTRAIN  \
0        -0.30686E-05                                             [2027]   
1        -0.16048E-04  [892, 4524, 6958, 6960, 7294, 7295, 12609, 12700]   
2        -0.11617E-04                                       [7080, 7081]   
3        -0.14572E-04                                            [11063]   
4        -0.23716E-03      

# processing material

In [28]:
material_data_f = [re.split(',', l.strip()) for l in material_data[1:-8]]
material_data_new = [i for i in material_data_f if "EX" in i]
# material_data_new

In [29]:
material_df = pd.DataFrame(material_data_new, columns=['A', 'B', 'C', 'D', 'Material', 'F', 'Final_value', 'H'])
final_material_df = material_df[['Material', 'Final_value']]

In [31]:
# final_material_df.head

In [38]:
# materials_e_stress_max = results_df['ELEMENT_EQUIVALENTSTRESS_max'].values
material = final_material_df['Material'].astype(int).values
final_val = final_material_df['Final_value'].astype(float).astype(int).values

In [42]:
# materials_e_stress_max = [i.tolist() for i in results_df['ELEMENT_EQUIVALENTSTRESS_max'].tolist()]
# range_val = [len(i) for i in  results_df['ELEMENT_EQUIVALENTSTRESS_max']]
# range_val
material

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [43]:
final_val

array([    0,     0,     0,     0,     0,     0,     0,     8,    31,
          71,   130,   209,   311,   435,   583,   757,   956,  1181,
        1434,  1715,  2024,  2362,  2731,  3129,  3558,  4019,  4511,
        5036,  5593,  6184,  6808,  7466,  8159,  8886,  9648, 10446,
       11280, 12151, 13057, 14001, 14982, 16001, 17057, 18152, 19285,
       20457, 21668, 22918, 24208, 25538, 26908])

In [47]:
master_list = dict(zip(material, final_val))

In [48]:
element_p_strain_max_new = results_df['ELEMENT_PRINCIPALSTRAIN_max'].values
element_p_strain_max_new

array([{8, 9, 10, 11, 13, 17, 18, 19, 21}, {8, 9, 10, 5}, {9, 4, 5, 7},
       {10, 11, 12, 13, 15, 18, 19}, {39, 27, 37, 31}, {11, 13, 15}, {18},
       {42, 43, 36}, {12, 13, 14}], dtype=object)

In [55]:
for row in element_p_strain_max_new:
    for items in row:
        print(master_list[items])
    
        
       

8 ==>  31
9 ==>  71
10 ==>  130
11 ==>  209
13 ==>  435
17 ==>  1181
18 ==>  1434
19 ==>  1715
21 ==>  2362
8 ==>  31
9 ==>  71
10 ==>  130
5 ==>  0
9 ==>  71
4 ==>  0
5 ==>  0
7 ==>  8
10 ==>  130
11 ==>  209
12 ==>  311
13 ==>  435
15 ==>  757
18 ==>  1434
19 ==>  1715
39 ==>  14001
27 ==>  5036
37 ==>  12151
31 ==>  7466
11 ==>  209
13 ==>  435
15 ==>  757
18 ==>  1434
42 ==>  17057
43 ==>  18152
36 ==>  11280
12 ==>  311
13 ==>  435
14 ==>  583


In [138]:
helper_function(main_arr, 2, 0)
helper_function(main_arr, 1, 1)
main_arr

IndexError: list index out of range

In [137]:
# for val in range_val:
#     for i in range(val):
#         print(i)
# [i for val in range_val for i in range(val)]
# map(list, range_val)
# another_list = [A, B, C]
[
    [a, b],
    [c],
    []
]

NameError: name 'a' is not defined

In [114]:
materials_e_stress_max

[[39, 41],
 [40],
 [30, 36, 36, 36, 36, 29, 37, 34, 18, 30, 33, 10],
 [6, 8, 19, 8, 6, 14, 21, 9, 14, 9, 17, 8, 8, 11, 12, 6, 8, 11, 10],
 [],
 [],
 [10, 11, 13, 10, 10, 10],
 [38, 37, 33, 33, 39, 37, 38, 38, 38, 33],
 [14, 26, 21, 16, 25, 23, 27, 26, 19, 19, 22, 24, 24, 24]]

In [83]:
final_value_e_stress_max = [[]]*len(materials_e_stress_max)
for i in range(len(materials_e_stress_max)):
    try:
        for j in range(materials_e_stress_max[i]): # j value 0,1
            for i1 in np.where(materials_e_stress_max[i][j]== material):
                    final_value_e_stress_max[i][j]= final_val[i1]
    except IndexError:
        final_value_e_stress_max[i] = []


2
1
12
19
0
0
6
10
14
2
1
12
19
0
0
6
10
14
2
1
12
19
0
0
6
10
14
2
1
12
19
0
0
6
10
14
2
1
12
19
0
0
6
10
14
2
1
12
19
0
0
6
10
14
2
1
12
19
0
0
6
10
14
2
1
12
19
0
0
6
10
14
2
1
12
19
0
0
6
10
14


In [79]:
final_value_e_stress_max

[array([14001]),
 array([14982]),
 array([6808]),
 array([0]),
 [],
 [],
 array([130]),
 array([13057]),
 array([583])]

In [20]:
final_material_df

Material Final_value
0         0           0
1         1        0.09
2         2        0.12
3         3        0.17
4         4        0.22
5         5        0.28
6         6        0.34
7         7        8.62
8         8       31.35
9         9       71.23
10       10      130.17
11       11      209.69
12       12      311.08
13       13      435.47
14       14      583.85
15       15      757.14
16       16      956.17
17       17     1181.72
18       18     1434.50
19       19     1715.20
20       20     2024.46
21       21     2362.87
22       22     2731.02
23       23     3129.46
24       24     3558.71
25       25     4019.28
26       26     4511.66
27       27     5036.32
28       28     5593.70
29       29     6184.25
30       30     6808.40
31       31     7466.54
32       32     8159.09
33       33     8886.43
34       34     9648.94
35       35    10446.99
36       36    11280.94
37       37    12151.13
38       38    13057.92
39       39    14001.63
40       40    14982.60
41       41    16001.14
42       42    17057.57
43       43    18152.20
44       44    19285.33
45       45    20457.26
46       46    21668.27
47       47    22918.66
48       48    24208.70
49       49    25538.66
50       50    26908.83